/**
 * @file        artifacts/ai-command-center/src/api/chat.ts
 * @module      AI Command Center / API
 * @purpose     Chat and conversation API with messaging, file uploads, summarization, and grounding features
 *
 * @ai_instructions
 *   - All message roles must be from the predefined union types.
 *   - File upload functions must handle progress callbacks and errors.
 *   - Summarization functions should only operate on conversations with sufficient message count.
 *   - Grounding modes must be validated before setting on threads.
 *   - DO NOT modify message structure without updating UI components.
 *
 * @exports     FileAttachment, MessageFeedback, MessageVersion, Citation, GroundingMode, Message, ConversationSummary, Thread, mockThreads, getThreads, getThread, sendMessage, uploadFile, sendMessageWithFiles, deleteThread, createThread, renameThread, generateThreadTitle, createBranchFromMessage, searchMessages, submitFeedback, updateFeedback, updateMessage, getMessageVersions, restoreMessageVersion, regenerateResponse, generateSummary, updateSummary, shouldAutoSummarize, setThreadGroundingMode
 * @imports     ./client
 *
 * @copyright   SPDX-FileCopyrightText: 2025 Trevor Lam <trevor@example.org>
 * @license     SPDX-License-Identifier: MIT
 */

import { mockFetch } from "./client";

export interface FileAttachment {
  id: string;
  name: string;
  type: string;
  size: number;
  url?: string;
}

export interface MessageFeedback {
  id: string;
  messageId: string;
  rating: 'positive' | 'negative';
  category?: 'inaccurate' | 'not_relevant' | 'incomplete' | 'harmful';
  comment?: string;
  timestamp: string;
}

export interface MessageVersion {
  id: string;
  messageId: string;
  content: string;
  timestamp: string;
  isCurrent: boolean;
}

export interface Citation {
  number: number;
  title: string;
  url?: string;
  snippet: string;
  sourceType: 'web' | 'knowledge_base' | 'document';
  domain?: string;
  publishedAt?: string;
}

export type GroundingMode = 'web' | 'knowledge_base' | 'none';

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'tool_call' | 'tool_result' | 'system';
  content: string;
  timestamp: string;
  toolCalls?: { name: string; args: string }[];
  toolResult?: { success: boolean; result: string };
  agentId?: string;
  attachments?: FileAttachment[];
  feedback?: MessageFeedback;
  // Editing and versioning metadata
  isEdited?: boolean;
  editedAt?: string;
  originalContent?: string;
  versions?: MessageVersion[];
  // Grounding and citations
  sources?: Citation[];
  confidence?: number; // 0–1
  groundingMode?: GroundingMode;
  isGrounded?: boolean;
}

export interface ConversationSummary {
  id: string;
  threadId: string;
  keyPoints: string[];
  actionItems: string[];
  overallSummary: string;
  messageCount: number;
  generatedAt: string;
  lastUpdated: string;
  isAutoGenerated: boolean;
}

export interface Thread {
  id: string;
  title: string;
  projectId: string;
  messages: Message[];
  updatedAt: string;
  parentThreadId?: string;
  branchPointMessageId?: string;
  summary?: ConversationSummary;
  groundingMode?: GroundingMode;
}

export const mockThreads: Thread[] = [
  {
    id: "thread-1",
    title: "Code Review: Authentication Service",
    projectId: "proj-1",
    updatedAt: new Date().toISOString(),
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Can you review the new OAuth2 implementation in the auth service? Specifically check for token leakage vulnerabilities.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      },
      {
        id: "m2",
        role: "assistant",
        content: "I will review the authentication service for you, focusing on the OAuth2 implementation and token security.",
        timestamp: new Date(Date.now() - 1000 * 60 * 59).toISOString(),
        agentId: "agent-3" // CodeReviewer
      },
      {
        id: "m3",
        role: "tool_call",
        content: "Checking out repository",
        timestamp: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
        toolCalls: [{ name: "git_clone", args: '{"repo":"auth-service", "branch":"feature/oauth2"}' }],
        agentId: "agent-3"
      },
      {
        id: "m4",
        role: "tool_result",
        content: "Repository cloned successfully to /tmp/workspace/auth-service",
        timestamp: new Date(Date.now() - 1000 * 60 * 57).toISOString(),
        toolResult: { success: true, result: "Cloned 45 objects." }
      },
      {
        id: "m5",
        role: "tool_call",
        content: "Analyzing token handlers",
        timestamp: new Date(Date.now() - 1000 * 60 * 56).toISOString(),
        toolCalls: [{ name: "grep_code", args: '{"pattern":"localStorage", "path":"src/utils/token.ts"}' }],
        agentId: "agent-3"
      },
      {
        id: "m6",
        role: "tool_result",
        content: "Found 2 instances of localStorage usage",
        timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
        toolResult: { success: true, result: "12: localStorage.setItem('access_token', token);\n13: localStorage.setItem('refresh_token', refresh);" }
      },
      {
        id: "m7",
        role: "assistant",
        content: "I found a critical security issue in `src/utils/token.ts`. You are storing both the access token and the refresh token in `localStorage`. This makes them vulnerable to XSS attacks [1]. I strongly recommend moving them to HttpOnly, Secure cookies [2]. According to OWASP security guidelines [3], tokens stored in `localStorage` can be accessed by any JavaScript running on the page, making them susceptible to cross-site scripting attacks.",
        timestamp: new Date(Date.now() - 1000 * 60 * 54).toISOString(),
        agentId: "agent-3",
        isGrounded: true,
        groundingMode: 'knowledge_base' as const,
        confidence: 0.92,
        sources: [
          {
            number: 1,
            title: "OWASP XSS Prevention Cheat Sheet",
            url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
            snippet: "localStorage and sessionStorage are accessible to JavaScript on the same domain, making them vulnerable to XSS attacks. Sensitive tokens should be stored in HttpOnly cookies to prevent script access.",
            sourceType: 'knowledge_base' as const,
            domain: "owasp.org",
            publishedAt: "2024-01-15",
          },
          {
            number: 2,
            title: "MDN Web Docs: HttpOnly cookies",
            url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies",
            snippet: "The HttpOnly attribute restricts access to cookies from JavaScript, meaning document.cookie cannot access HttpOnly cookies, which helps mitigate XSS attacks on authentication tokens.",
            sourceType: 'web' as const,
            domain: "developer.mozilla.org",
          },
          {
            number: 3,
            title: "JWT Security Best Practices — Auth0",
            url: "https://auth0.com/blog/a-look-at-the-latest-draft-for-jwt-bcp/",
            snippet: "Never store tokens in localStorage or sessionStorage when security is a concern. Use HttpOnly cookies with SameSite=Strict to mitigate both CSRF and XSS risks simultaneously.",
            sourceType: 'web' as const,
            domain: "auth0.com",
          },
        ],
      }
    ]
  },
  {
    id: "thread-2",
    title: "Data Migration Plan",
    projectId: "proj-2",
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    messages: [
      {
        id: "m21",
        role: "user",
        content: "We need to migrate the legacy users table to the new schema. Can you outline a plan?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
      },
      {
        id: "m22",
        role: "assistant",
        content: "I'll analyze the current schema and propose a migration strategy.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25 + 5000).toISOString(),
        agentId: "agent-4" // DataAnalyst
      }
    ]
  }
];

export const getThreads = () => mockFetch(mockThreads, 300);
export const getThread = (id: string) => {
  const t = mockThreads.find(x => x.id === id);
  if (!t) return Promise.reject(new Error("Thread not found"));
  return mockFetch(t, 200);
};

export const sendMessage = (threadId: string, content: string, attachments?: FileAttachment[]) => {
  return mockFetch({
    id: `m-new-${Date.now()}`,
    role: 'user',
    content,
    timestamp: new Date().toISOString(),
    attachments: attachments || []
  } as Message, 500);
};

// AI-WARN: File upload function handles sensitive data - ensure proper validation and error handling
export const uploadFile = (file: File, onProgress?: (progress: number) => void): Promise<{ url: string }> => {
  return new Promise((resolve, reject) => {
    const formData = new FormData();
    formData.append('file', file);

    // AI-NOTE: Using XMLHttpRequest for progress tracking instead of fetch
    const xhr = new XMLHttpRequest();

    if (onProgress) {
      xhr.upload.addEventListener('progress', (e) => {
        if (e.lengthComputable) {
          const progress = (e.loaded / e.total) * 100;
          onProgress(Math.round(progress));
        }
      });
    }

    // AI-NOTE: Response parsing must handle both success and error cases
    xhr.addEventListener('load', () => {
      if (xhr.status === 200) {
        try {
          // AI-WARN: JSON parsing can throw - ensure proper error handling
          const response = JSON.parse(xhr.responseText);
          resolve({
            url: response.url || `/uploads/${file.name}`
          });
        } catch (error) {
          reject(new Error('Invalid server response'));
        }
      } else {
        reject(new Error(`Upload failed: ${xhr.statusText}`));
      }
    });

    xhr.addEventListener('error', () => {
      reject(new Error('Network error during upload'));
    });

    xhr.open('POST', '/api/upload');
    xhr.send(formData);
  });
};

export const sendMessageWithFiles = async (
  threadId: string, 
  content: string, 
  files: File[],
  onProgress?: (fileId: string, progress: number) => void
): Promise<Message> => {
  // Upload files first
  const uploadPromises = files.map(async (file, index) => {
    const fileId = `file-${index}-${Date.now()}`;
    
    const uploadResult = await uploadFile(file, (progress) => {
      onProgress?.(fileId, progress);
    });

    return {
      id: fileId,
      name: file.name,
      type: file.type,
      size: file.size,
      url: uploadResult.url
    } as FileAttachment;
  });

  try {
    const attachments = await Promise.all(uploadPromises);
    
    // Send message with attachments
    return await sendMessage(threadId, content, attachments);
  } catch (error) {
    throw new Error(`Failed to upload files: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

export const deleteThread = (threadId: string): Promise<void> => {
  return mockFetch(undefined, 500).then(() => {
    // In a real implementation, this would make a DELETE request to the server
    // For now, we'll simulate the deletion
    const index = mockThreads.findIndex(t => t.id === threadId);
    if (index > -1) {
      mockThreads.splice(index, 1);
    }
  });
};

export const createThread = (projectId: string, initialTitle: string = "New Thread"): Promise<Thread> => {
  return mockFetch(undefined, 300).then(() => {
    const newThread: Thread = {
      id: `thread-${Date.now()}`,
      title: initialTitle,
      projectId,
      messages: [],
      updatedAt: new Date().toISOString(),
    };
    mockThreads.unshift(newThread);
    return { ...newThread };
  });
};

export const renameThread = (threadId: string, newTitle: string): Promise<Thread> => {
  return mockFetch(undefined, 300).then(() => {
    // In a real implementation, this would make a PATCH request to the server
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }
    
    thread.title = newTitle;
    thread.updatedAt = new Date().toISOString();
    
    return { ...thread };
  });
};

export const generateThreadTitle = (messageContent: string): string => {
  if (!messageContent) return "New Thread";
  const cleanContent = messageContent.trim();
  if (cleanContent.length <= 40) return cleanContent;
  return cleanContent.substring(0, 37) + "...";
};

export const createBranchFromMessage = (
  parentThreadId: string,
  branchPointMessageId: string,
  newTitle?: string
): Promise<Thread> => {
  return mockFetch(undefined, 400).then(() => {
    // Find the parent thread
    const parentThread = mockThreads.find(t => t.id === parentThreadId);
    if (!parentThread) {
      throw new Error('Parent thread not found');
    }

    // Find the branch point message index
    const branchPointIndex = parentThread.messages.findIndex(m => m.id === branchPointMessageId);
    if (branchPointIndex === -1) {
      throw new Error('Branch point message not found');
    }

    // Create new thread with messages up to and including the branch point
    const branchMessages = parentThread.messages.slice(0, branchPointIndex + 1);
    
    const newThread: Thread = {
      id: `thread-${Date.now()}`,
      title: newTitle || `${parentThread.title} (branch)`,
      projectId: parentThread.projectId,
      messages: branchMessages,
      updatedAt: new Date().toISOString(),
      parentThreadId,
      branchPointMessageId,
    };

    // Add to the beginning of mockThreads
    mockThreads.unshift(newThread);
    return { ...newThread };
  });
};

export const searchMessages = (threadId: string, query: string): Promise<string[]> => {
  return mockFetch(undefined, 200).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread || !query.trim()) return [];
    
    const searchTerms = query.toLowerCase().trim();
    return thread.messages
      .filter(m => m.content.toLowerCase().includes(searchTerms))
      .map(m => m.id);
  });
};

export const submitFeedback = (
  messageId: string,
  rating: 'positive' | 'negative',
  category?: 'inaccurate' | 'not_relevant' | 'incomplete' | 'harmful',
  comment?: string
): Promise<MessageFeedback> => {
  return mockFetch({
    id: `feedback-${Date.now()}`,
    messageId,
    rating,
    category,
    comment,
    timestamp: new Date().toISOString(),
  }, 300);
};

export const updateFeedback = (
  feedbackId: string,
  updates: Partial<MessageFeedback>
): Promise<MessageFeedback> => {
  return mockFetch(undefined, 300).then(() => {
    // In a real implementation, this would update the feedback in the database
    // For now, we'll just return the updated feedback
    return {
      id: feedbackId,
      messageId: '',
      rating: 'positive',
      timestamp: new Date().toISOString(),
      ...updates,
    } as MessageFeedback;
  });
};

// Message editing and versioning functions
export const updateMessage = (
  threadId: string,
  messageId: string,
  newContent: string
): Promise<Message> => {
  return mockFetch(undefined, 400).then(() => {
    // Find the thread and message
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }

    const messageIndex = thread.messages.findIndex(m => m.id === messageId);
    if (messageIndex === -1) {
      throw new Error('Message not found');
    }

    const message = thread.messages[messageIndex];
    
    // Create version history if not exists
    if (!message.versions) {
      message.versions = [{
        id: `version-${Date.now()}`,
        messageId: message.id,
        content: message.content,
        timestamp: message.timestamp,
        isCurrent: false
      }];
    }

    // Add current version to history
    message.versions.push({
      id: `version-${Date.now()}`,
      messageId: message.id,
      content: message.content,
      timestamp: message.timestamp,
      isCurrent: false
    });

    // Update message content and metadata
    const originalContent = message.originalContent || message.content;
    message.content = newContent;
    message.originalContent = originalContent;
    message.isEdited = true;
    message.editedAt = new Date().toISOString();
    message.timestamp = new Date().toISOString(); // Update timestamp for sorting

    // Update thread timestamp
    thread.updatedAt = new Date().toISOString();

    return { ...message };
  });
};

export const getMessageVersions = (
  threadId: string,
  messageId: string
): Promise<MessageVersion[]> => {
  return mockFetch(undefined, 200).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }

    const message = thread.messages.find(m => m.id === messageId);
    if (!message) {
      throw new Error('Message not found');
    }

    // Return versions including current version
    const versions = message.versions || [];
    const currentVersion: MessageVersion = {
      id: `version-current-${Date.now()}`,
      messageId: message.id,
      content: message.content,
      timestamp: message.timestamp,
      isCurrent: true
    };

    return [...versions, currentVersion].sort((a, b) => 
      new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );
  });
};

export const restoreMessageVersion = (
  threadId: string,
  messageId: string,
  versionId: string
): Promise<Message> => {
  return mockFetch(undefined, 400).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }

    const message = thread.messages.find(m => m.id === messageId);
    if (!message) {
      throw new Error('Message not found');
    }

    // Find the version to restore
    const versions = message.versions || [];
    const versionToRestore = versions.find(v => v.id === versionId);
    if (!versionToRestore) {
      throw new Error('Version not found');
    }

    // Add current content to versions before restoring
    if (!message.versions) {
      message.versions = [];
    }
    message.versions.push({
      id: `version-${Date.now()}`,
      messageId: message.id,
      content: message.content,
      timestamp: message.timestamp,
      isCurrent: false
    });

    // Restore the version content
    message.content = versionToRestore.content;
    message.editedAt = new Date().toISOString();
    message.timestamp = new Date().toISOString();
    thread.updatedAt = new Date().toISOString();

    return { ...message };
  });
};

export const regenerateResponse = (
  threadId: string,
  userMessageId: string
): Promise<Message> => {
  return mockFetch(undefined, 1500).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }

    const userMessageIndex = thread.messages.findIndex(m => m.id === userMessageId);
    if (userMessageIndex === -1) {
      throw new Error('User message not found');
    }

    // Find and remove the assistant response that follows the user message
    const assistantMessageIndex = userMessageIndex + 1;
    if (assistantMessageIndex < thread.messages.length && 
        thread.messages[assistantMessageIndex].role === 'assistant') {
      // Remove the old assistant response
      thread.messages.splice(assistantMessageIndex, 1);
    }

    // Generate a new response
    const newResponse: Message = {
      id: `assistant-regen-${Date.now()}`,
      role: 'assistant',
      content: `I've regenerated my response based on your updated message: "${thread.messages[userMessageIndex].content}". Let me provide a fresh perspective on this...`,
      timestamp: new Date().toISOString(),
      agentId: 'agent-3'
    };

    // Insert the new response after the user message
    thread.messages.splice(userMessageIndex + 1, 0, newResponse);
    thread.updatedAt = new Date().toISOString();

    return newResponse;
  });
};

// Conversation Summarization Functions
export const generateSummary = async (
  threadId: string,
  options?: { isAutoGenerated?: boolean }
): Promise<ConversationSummary> => {
  return mockFetch(undefined, 2000).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }

    // Filter out system messages and tool calls for cleaner summarization
    const conversationMessages = thread.messages.filter(
      m => m.role === 'user' || m.role === 'assistant'
    );

    if (conversationMessages.length < 3) {
      throw new Error('Thread too short for summarization');
    }

    // Simulate AI-generated summary based on conversation content
    const now = new Date().toISOString();
    const summary: ConversationSummary = {
      id: `summary-${threadId}-${Date.now()}`,
      threadId,
      keyPoints: extractKeyPoints(conversationMessages),
      actionItems: extractActionItems(conversationMessages),
      overallSummary: generateOverallSummary(conversationMessages),
      messageCount: conversationMessages.length,
      generatedAt: now,
      lastUpdated: now,
      isAutoGenerated: options?.isAutoGenerated ?? false
    };

    // Update thread with summary
    thread.summary = summary;
    thread.updatedAt = now;

    return summary;
  });
};

export const updateSummary = async (
  threadId: string,
  summaryId: string
): Promise<ConversationSummary> => {
  const thread = mockThreads.find(t => t.id === threadId);
  if (!thread || !thread.summary) {
    throw new Error('Thread or summary not found');
  }

  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1500));

  // Regenerate summary with updated conversation
  const updatedSummary = await generateSummary(threadId, { 
    isAutoGenerated: thread.summary.isAutoGenerated 
  });

  // Preserve original ID and generation time
  updatedSummary.id = summaryId;
  updatedSummary.generatedAt = thread.summary.generatedAt;

  thread.summary = updatedSummary;
  thread.updatedAt = new Date().toISOString();

  return updatedSummary;
};

export const shouldAutoSummarize = (thread: Thread): boolean => {
  // Auto-summarize when thread has more than 15 messages
  const messageThreshold = 15;
  const conversationMessages = thread.messages.filter(
    m => m.role === 'user' || m.role === 'assistant'
  );
  
  return conversationMessages.length >= messageThreshold && !thread.summary;
};

// Helper functions for content analysis (in real implementation, these would call an AI service)
function extractKeyPoints(messages: Message[]): string[] {
  // Simulate key point extraction based on message content
  const keyPoints: string[] = [];
  
  messages.forEach(msg => {
    if (msg.role === 'assistant') {
      if (msg.content.includes('security') || msg.content.includes('vulnerability')) {
        keyPoints.push('Critical security vulnerabilities identified in authentication system');
      }
      if (msg.content.includes('token') || msg.content.includes('localStorage')) {
        keyPoints.push('Token storage security issues require immediate attention');
      }
      if (msg.content.includes('migration') || msg.content.includes('schema')) {
        keyPoints.push('Data migration planning for legacy user table');
      }
    }
  });

  return keyPoints.length > 0 ? keyPoints : ['Key discussion points extracted from conversation'];
}

function extractActionItems(messages: Message[]): string[] {
  // Simulate action item extraction
  const actionItems: string[] = [];
  
  messages.forEach(msg => {
    if (msg.role === 'assistant') {
      if (msg.content.includes('recommend')) {
        actionItems.push('Review and implement recommended security fixes');
      }
      if (msg.content.includes('migration')) {
        actionItems.push('Plan and execute database migration');
      }
    }
  });

  return actionItems.length > 0 ? actionItems : ['Follow up on discussed action items'];
}

function generateOverallSummary(messages: Message[]): string {
  const userMessages = messages.filter(m => m.role === 'user');
  const assistantMessages = messages.filter(m => m.role === 'assistant');
  
  if (userMessages.length === 0) return 'No conversation to summarize';
  
  const firstUserMessage = userMessages[0].content.toLowerCase();
  let summary = '';
  
  if (firstUserMessage.includes('review') || firstUserMessage.includes('audit')) {
    summary = 'Code review session focused on authentication service security';
  } else if (firstUserMessage.includes('migration') || firstUserMessage.includes('data')) {
    summary = 'Discussion about data migration strategies and implementation';
  } else {
    summary = `Conversation covering ${messages.length} messages between user and assistant`;
  }
  
  summary += `. Key topics include security vulnerabilities, token storage, and implementation recommendations.`;
  
  return summary;
}

// Grounding Mode Management
export const setThreadGroundingMode = (
  threadId: string,
  mode: GroundingMode
): Promise<Thread> => {
  return mockFetch(undefined, 100).then(() => {
    const thread = mockThreads.find(t => t.id === threadId);
    if (!thread) {
      throw new Error('Thread not found');
    }
    thread.groundingMode = mode;
    thread.updatedAt = new Date().toISOString();
    return { ...thread };
  });
};
