// Test file to verify summarization functionality
import { generateSummary, updateSummary, shouldAutoSummarize } from './api/chat';

async function testSummarization() {
  console.log('Testing AI-Powered Conversation Summarization...');
  
  try {
    // Test with thread-1 (has enough messages for summarization)
    const summary = await generateSummary('thread-1', { isAutoGenerated: false });
    console.log('✅ Summary generated:', summary);
    
    // Test update summary
    const updatedSummary = await updateSummary('thread-1', summary.id);
    console.log('✅ Summary updated:', updatedSummary);
    
    console.log('✅ All summarization tests passed!');
  } catch (error) {
    console.error('❌ Test failed:', error);
  }
}

// Export for manual testing
export { testSummarization };
