/**
 * @file        lib/db/src/schema/chat.ts
 * @module      Database / Schema / Chat
 * @purpose     Chat and message schema for conversation management with versioning and RAG support
 *
 * @ai_instructions
 *   - Follow multi-tenant patterns using tenantColumn from helpers.ts
 *   - Apply RLS policies for tenant isolation
 *   - Use pgEnum for status fields with documented state transitions
 *   - Include proper indexes for performance with RLS
 *   - Use pgvector for embedding storage with vector(1536) for OpenAI compatibility
 *   - Follow existing schema patterns from agents.ts and approvals.ts
 *   - Implement immutable message history via versioning
 *
 * @exports     chat_threads, messages, message_versions, citations, summaries, feedback, attachments, embeddings_chunks tables and types
 * @imports     drizzle-orm/pg-core, drizzle-zod, zod, ./helpers
 *
 * @copyright   SPDX-FileCopyrightText: 2025 Trevor Lam <trevor@example.org>
 * @license     SPDX-License-Identifier: MIT
 */

import { 
  pgTable, 
  text, 
  uuid, 
  timestamp, 
  integer,
  jsonb,
  pgEnum,
  index,
  decimal,
  boolean,
  unique,
  vector
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { tenantColumn } from "./helpers";

// Message role enum for different message types
export const messageRoleEnum = pgEnum("message_role", [
  "user",
  "assistant", 
  "tool_call",
  "tool_result",
  "system"
]);

// Grounding mode enum for citation sources
export const groundingModeEnum = pgEnum("grounding_mode", [
  "none",
  "web", 
  "knowledge_base",
  "document"
]);

// Citation source type enum
export const citationSourceTypeEnum = pgEnum("citation_source_type", [
  "web",
  "knowledge_base", 
  "document"
]);

// Feedback rating enum
export const feedbackRatingEnum = pgEnum("feedback_rating", [
  "positive",
  "negative"
]);

// Feedback category enum for classification
export const feedbackCategoryEnum = pgEnum("feedback_category", [
  "accuracy",
  "relevance",
  "clarity",
  "helpfulness",
  "safety",
  "other"
]);

/**
 * Chat threads table - Main conversation containers
 */
export const chatThreadsTable = pgTable("chat_threads", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: tenantColumn.notNull(),
  title: text("title").notNull(),
  projectId: text("project_id"), // Optional project association
  parentThreadId: uuid("parent_thread_id"), // For conversation branching
  branchPointMessageId: uuid("branch_point_message_id"), // Where this thread branched from
  groundingMode: groundingModeEnum("grounding_mode").default("none").notNull(),
  summaryId: uuid("summary_id"), // Reference to latest summary
  messageCount: integer("message_count").default(0).notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  metadata: jsonb("metadata"), // Additional thread metadata
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes for RLS and common queries
  tenantIdx: index("idx_chat_threads_tenant").on(table.tenantId),
  tenantProjectIdx: index("idx_chat_threads_tenant_project").on(table.tenantId, table.projectId),
  tenantActiveIdx: index("idx_chat_threads_tenant_active").on(table.tenantId, table.isActive),
  parentIdx: index("idx_chat_threads_parent").on(table.parentThreadId),
  createdAtIdx: index("idx_chat_threads_created_at").on(table.createdAt),
  updatedAtIdx: index("idx_chat_threads_updated_at").on(table.updatedAt),
}));

/**
 * Messages table - Core message storage
 */
export const messagesTable = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  threadId: uuid("thread_id").notNull().references(() => chatThreadsTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  role: messageRoleEnum("role").notNull(),
  content: text("content").notNull(),
  agentId: uuid("agent_id"), // Reference to agent if generated by AI
  isEdited: boolean("is_edited").default(false).notNull(),
  editedAt: timestamp("edited_at", { mode: "string" }),
  groundingMode: groundingModeEnum("grounding_mode").default("none").notNull(),
  confidenceScore: decimal("confidence_score", { precision: 3, scale: 2 }), // 0.00-1.00
  tokenCount: integer("token_count").default(0),
  metadata: jsonb("metadata"), // Additional message metadata
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes for RLS and common queries
  tenantIdx: index("idx_messages_tenant").on(table.tenantId),
  threadTenantIdx: index("idx_messages_thread_tenant").on(table.threadId, table.tenantId),
  threadRoleIdx: index("idx_messages_thread_role").on(table.threadId, table.role),
  agentIdx: index("idx_messages_agent").on(table.agentId),
  createdAtIdx: index("idx_messages_created_at").on(table.createdAt),
}));

/**
 * Message versions table - Immutable history of message edits
 */
export const messageVersionsTable = pgTable("message_versions", {
  id: uuid("id").primaryKey().defaultRandom(),
  messageId: uuid("message_id").notNull().references(() => messagesTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  content: text("content").notNull(),
  isCurrent: boolean("is_current").default(false).notNull(),
  versionNumber: integer("version_number").notNull(),
  editReason: text("edit_reason"), // Optional reason for edit
  editedBy: text("edited_by"), // User who made the edit
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes
  tenantIdx: index("idx_message_versions_tenant").on(table.tenantId),
  messageTenantIdx: index("idx_message_versions_message_tenant").on(table.messageId, table.tenantId),
  currentIdx: index("idx_message_versions_current").on(table.isCurrent),
  messageVersionUniqueIdx: unique("idx_message_versions_unique").on(table.messageId, table.versionNumber),
}));

/**
 * Citations table - Source references for grounded responses
 */
export const citationsTable = pgTable("citations", {
  id: uuid("id").primaryKey().defaultRandom(),
  messageId: uuid("message_id").notNull().references(() => messagesTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  number: integer("number").notNull(), // Citation number in message [1], [2], etc.
  title: text("title").notNull(),
  url: text("url"),
  snippet: text("snippet").notNull(),
  sourceType: citationSourceTypeEnum("source_type").notNull(),
  domain: text("domain"),
  publishedAt: timestamp("published_at", { mode: "string" }),
  relevanceScore: decimal("relevance_score", { precision: 3, scale: 2 }),
  metadata: jsonb("metadata"), // Additional citation metadata
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes
  tenantIdx: index("idx_citations_tenant").on(table.tenantId),
  messageTenantIdx: index("idx_citations_message_tenant").on(table.messageId, table.tenantId),
  sourceTypeIdx: index("idx_citations_source_type").on(table.sourceType),
  domainIdx: index("idx_citations_domain").on(table.domain),
}));

/**
 * Summaries table - Thread summaries and key points extraction
 */
export const summariesTable = pgTable("summaries", {
  id: uuid("id").primaryKey().defaultRandom(),
  threadId: uuid("thread_id").notNull().references(() => chatThreadsTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  keyPoints: jsonb("key_points").notNull(), // Array of key points
  actionItems: jsonb("action_items").notNull(), // Array of action items
  overallSummary: text("overall_summary").notNull(),
  messageCount: integer("message_count").notNull(),
  generatedAt: timestamp("generated_at", { mode: "string" }).defaultNow().notNull(),
  lastUpdated: timestamp("last_updated", { mode: "string" }).defaultNow().notNull(),
  isAutoGenerated: boolean("is_auto_generated").default(true).notNull(),
  modelUsed: text("model_used"), // AI model used for generation
  metadata: jsonb("metadata"), // Additional summary metadata
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes
  tenantIdx: index("idx_summaries_tenant").on(table.tenantId),
  threadTenantIdx: index("idx_summaries_thread_tenant").on(table.threadId, table.tenantId),
  generatedAtIdx: index("idx_summaries_generated_at").on(table.generatedAt),
}));

/**
 * Feedback table - User feedback on messages
 */
export const feedbackTable = pgTable("feedback", {
  id: uuid("id").primaryKey().defaultRandom(),
  messageId: uuid("message_id").notNull().references(() => messagesTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  userId: text("user_id").notNull(), // User who provided feedback
  rating: feedbackRatingEnum("rating").notNull(),
  category: feedbackCategoryEnum("category").notNull(),
  comment: text("comment"), // Optional detailed feedback
  context: jsonb("context"), // Additional context at feedback time
  isHelpful: boolean("is_helpful"), // For quick thumbs up/down
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes and constraints
  tenantIdx: index("idx_feedback_tenant").on(table.tenantId),
  messageTenantIdx: index("idx_feedback_message_tenant").on(table.messageId, table.tenantId),
  userMessageUniqueIdx: unique("idx_feedback_user_message_unique").on(table.userId, table.messageId),
  ratingIdx: index("idx_feedback_rating").on(table.rating),
  categoryIdx: index("idx_feedback_category").on(table.category),
}));

/**
 * Attachments table - File attachments for messages
 */
export const attachmentsTable = pgTable("attachments", {
  id: uuid("id").primaryKey().defaultRandom(),
  messageId: uuid("message_id").notNull().references(() => messagesTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  storageReferenceId: text("storage_reference_id").notNull(), // Reference to storage system
  name: text("name").notNull(),
  type: text("type").notNull(), // MIME type
  size: integer("size").notNull(), // File size in bytes
  url: text("url"), // Direct access URL
  thumbnailUrl: text("thumbnail_url"), // Thumbnail for images
  metadata: jsonb("metadata"), // Additional attachment metadata
  isProcessed: boolean("is_processed").default(false).notNull(),
  processingError: text("processing_error"),
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes
  tenantIdx: index("idx_attachments_tenant").on(table.tenantId),
  messageTenantIdx: index("idx_attachments_message_tenant").on(table.messageId, table.tenantId),
  typeIdx: index("idx_attachments_type").on(table.type),
}));

/**
 * Embedding chunks table - Vector embeddings for RAG and semantic search
 * Uses pgvector extension with vector(1536) for OpenAI compatibility
 */
export const embeddingChunksTable = pgTable("embedding_chunks", {
  id: uuid("id").primaryKey().defaultRandom(),
  threadId: uuid("thread_id").notNull().references(() => chatThreadsTable.id, { onDelete: "cascade" }),
  messageId: uuid("message_id").references(() => messagesTable.id, { onDelete: "cascade" }),
  tenantId: tenantColumn.notNull(),
  chunkText: text("chunk_text").notNull(),
  embedding: vector("embedding", { dimensions: 1536 }).notNull(), // pgvector for OpenAI compatibility
  chunkIndex: integer("chunk_index").notNull(), // Order within message
  embeddingModel: text("embedding_model").notNull(), // Model used to generate embedding
  metadata: jsonb("metadata"), // Additional chunk metadata
  createdAt: timestamp("created_at", { mode: "string" }).defaultNow().notNull()
}, (table) => ({
  // Performance indexes for vector search
  tenantIdx: index("idx_embedding_chunks_tenant").on(table.tenantId),
  threadTenantIdx: index("idx_embedding_chunks_thread_tenant").on(table.threadId, table.tenantId),
  messageTenantIdx: index("idx_embedding_chunks_message_tenant").on(table.messageId, table.tenantId),
  chunkIndexIdx: index("idx_embedding_chunks_chunk_index").on(table.chunkIndex),
}));

// Insert schemas with validation
export const insertChatThreadSchema = createInsertSchema(chatThreadsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  messageCount: true
});

export const insertMessageSchema = createInsertSchema(messagesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  isEdited: true,
  editedAt: true,
  tokenCount: true
});

export const insertMessageVersionSchema = createInsertSchema(messageVersionsTable).omit({
  id: true,
  createdAt: true
});

export const insertCitationSchema = createInsertSchema(citationsTable).omit({
  id: true,
  createdAt: true
});

export const insertSummarySchema = createInsertSchema(summariesTable).omit({
  id: true,
  createdAt: true,
  generatedAt: true,
  lastUpdated: true
});

export const insertFeedbackSchema = createInsertSchema(feedbackTable).omit({
  id: true,
  createdAt: true
});

export const insertAttachmentSchema = createInsertSchema(attachmentsTable).omit({
  id: true,
  createdAt: true,
  isProcessed: true,
  processingError: true
});

export const insertEmbeddingChunkSchema = createInsertSchema(embeddingChunksTable).omit({
  id: true,
  createdAt: true
});

// Type inference
export type ChatThread = typeof chatThreadsTable.$inferSelect;
export type InsertChatThread = typeof chatThreadsTable.$inferInsert;
export type Message = typeof messagesTable.$inferSelect;
export type InsertMessage = typeof messagesTable.$inferInsert;
export type MessageVersion = typeof messageVersionsTable.$inferSelect;
export type InsertMessageVersion = typeof messageVersionsTable.$inferInsert;
export type Citation = typeof citationsTable.$inferSelect;
export type InsertCitation = typeof citationsTable.$inferInsert;
export type Summary = typeof summariesTable.$inferSelect;
export type InsertSummary = typeof summariesTable.$inferInsert;
export type Feedback = typeof feedbackTable.$inferSelect;
export type InsertFeedback = typeof feedbackTable.$inferInsert;
export type Attachment = typeof attachmentsTable.$inferSelect;
export type InsertAttachment = typeof attachmentsTable.$inferInsert;
export type EmbeddingChunk = typeof embeddingChunksTable.$inferSelect;
export type InsertEmbeddingChunk = typeof embeddingChunksTable.$inferInsert;
